/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libreta.de.teléfonos;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Jse_0
 */
public class AgendaModificar extends javax.swing.JFrame {
    DefaultListModel datos_modificados = new DefaultListModel();
    public ListModel respaldo; 
    
    public void setRespaldo(ListModel res)
    {
        respaldo = res;
    }
    public ListModel getRespaldo()
    {
        return respaldo;
    }
    /**
     * Creates new form AgendaModificar
     */
    public AgendaModificar() {
        initComponents();
        DefaultListModel datosmod = LibretaDeTeléfonos.a.datos;
        lista.setModel(datosmod);
        
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contacto = new javax.swing.JDialog();
        texto_nombre = new javax.swing.JLabel();
        texto_telefono = new javax.swing.JLabel();
        texto_tipo = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        lista_contactos = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        modificar = new javax.swing.JButton();
        box_trabajo = new javax.swing.JCheckBox();
        box_movil = new javax.swing.JCheckBox();
        box_hogar = new javax.swing.JCheckBox();

        Contacto.setTitle("Modificar Contacto");

        texto_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto_nombre.setText("Nombre:");

        texto_telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto_telefono.setText("Teléfono:");

        texto_tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto_tipo.setText("Tipo:");

        tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRABAJO", "HOGAR", "MOVIL" }));

        aceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContactoLayout = new javax.swing.GroupLayout(Contacto.getContentPane());
        Contacto.getContentPane().setLayout(ContactoLayout);
        ContactoLayout.setHorizontalGroup(
            ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactoLayout.createSequentialGroup()
                        .addComponent(texto_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactoLayout.createSequentialGroup()
                        .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_telefono)
                            .addComponent(texto_tipo))
                        .addGap(21, 21, 21)
                        .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefono)
                            .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(ContactoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(aceptar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContactoLayout.setVerticalGroup(
            ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_nombre))
                .addGap(18, 18, 18)
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_telefono)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_tipo)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda telefónica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texto.setText("Lista de Contactos");

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista_contactos.setViewportView(lista);

        modificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        box_trabajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        box_trabajo.setSelected(true);
        box_trabajo.setText("Trabajo");
        box_trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_trabajoActionPerformed(evt);
            }
        });

        box_movil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        box_movil.setSelected(true);
        box_movil.setText("Movil");
        box_movil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_movilActionPerformed(evt);
            }
        });

        box_hogar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        box_hogar.setSelected(true);
        box_hogar.setText("Hogar");
        box_hogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_hogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lista_contactos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(texto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(box_trabajo)
                                .addGap(42, 42, 42)
                                .addComponent(box_hogar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(box_movil)
                                .addGap(24, 24, 24)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lista_contactos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_trabajo)
                    .addComponent(box_movil)
                    .addComponent(box_hogar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String datos_contacto;
    
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        if(lista.getSelectedValue() == null ) 
        {
            JOptionPane.showMessageDialog(null, "Seleccione el contacto que desea modificar", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else {
        datos_contacto = lista.getSelectedValue();
        
        int i = 0;
        while(!"-".equals(datos_contacto.substring(i, i+1)))
        {
            i++;
        }
        nombre.setText(datos_contacto.substring(0, i-1));
        i=i+2;
        int j = i;
        while(!"-".equals(datos_contacto.substring(i, i+1)))
        {
            i++;
        }
        telefono.setText(datos_contacto.substring(j,i-1));
        
        String tip = datos_contacto.substring(i+2, datos_contacto.length());
        
        switch (tip) {
            case "TRABAJO":
                tipo.setSelectedIndex(0);
                break;
            case "HOGAR":
                tipo.setSelectedIndex(1);
                break;
            default:
                tipo.setSelectedIndex(2);
                break;
        }
        
        Contacto.setLocationRelativeTo(null);
        Contacto.setSize(270,220);
        Contacto.setVisible(true);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void actualizarlista(String contacto_modificado) {
        datos_modificados.clear();
        int i = 0;
        while(!lista.getModel().getElementAt(i).equals(datos_contacto))
        {
            datos_modificados.addElement(lista.getModel().getElementAt(i));
            i++;
        }
        datos_modificados.addElement(contacto_modificado);
        i++;
        
        while(i < lista.getModel().getSize())
        {
            datos_modificados.addElement(lista.getModel().getElementAt(i));
            i++;
        }
        lista.setModel(datos_modificados);
        setRespaldo(datos_modificados);
    }
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String nom = nombre.getText();
        String num = telefono.getText();
        String tipoo = tipo.getSelectedItem().toString();
        
        String datos_modificado = nom + " - " + num + " - " + tipoo;
        
        actualizarlista(datos_modificado);
        
        Contacto.dispose();
        JOptionPane.showMessageDialog(null, "Contacto modificado", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Contacto.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void box_trabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_trabajoActionPerformed
        box();
    }//GEN-LAST:event_box_trabajoActionPerformed

    private void box_hogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_hogarActionPerformed
        box();
    }//GEN-LAST:event_box_hogarActionPerformed

    private void box_movilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_movilActionPerformed
        box();
    }//GEN-LAST:event_box_movilActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        lista.setModel(getRespaldo());
        box_trabajo.setSelected(true);
        box_hogar.setSelected(true);
        box_movil.setSelected(true);
    }//GEN-LAST:event_formWindowClosed
    
    private void box() {
        lista.setModel(getRespaldo());
        DefaultListModel nuevomodelo = new DefaultListModel();
        int i;
        if(box_trabajo.isSelected()) {
            for(i=0; i < lista.getModel().getSize(); i++) {
                if(lista.getModel().getElementAt(i).contains("TRABAJO")) {
                    nuevomodelo.addElement(lista.getModel().getElementAt(i));                        
                }
            }
        }
        if(box_hogar.isSelected()) {
            for(i=0; i < lista.getModel().getSize(); i++) {
                if(lista.getModel().getElementAt(i).contains("HOGAR")) {
                    nuevomodelo.addElement(lista.getModel().getElementAt(i));                        
                }
            }
        }
        if(box_movil.isSelected()) {
            for(i=0; i < lista.getModel().getSize(); i++) {
                if(lista.getModel().getElementAt(i).contains("MOVIL")) {
                    nuevomodelo.addElement(lista.getModel().getElementAt(i));                        
                }
            }
        }
        lista.setModel(nuevomodelo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Contacto;
    private javax.swing.JButton aceptar;
    private javax.swing.JCheckBox box_hogar;
    private javax.swing.JCheckBox box_movil;
    private javax.swing.JCheckBox box_trabajo;
    private javax.swing.JButton cancelar;
    public javax.swing.JList<String> lista;
    private javax.swing.JScrollPane lista_contactos;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto_nombre;
    private javax.swing.JLabel texto_telefono;
    private javax.swing.JLabel texto_tipo;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
